services:
  cinek:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cinek
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3002
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
