CREATE TABLE `movies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` varchar(50) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`name` varchar(500) NOT NULL,
	`origin_name` varchar(500),
	`thumb` text,
	`poster` text,
	`year` int,
	`time` varchar(100),
	`episode` varchar(100),
	`quality` varchar(50),
	`lang` varchar(50),
	`type` varchar(50),
	`rating` int,
	`content` text,
	`categories` json,
	`countries` json,
	`sources` json,
	`active` boolean NOT NULL DEFAULT false,
	`synced_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `movies_id` PRIMARY KEY(`id`)
);
